version: '3.4'

services:
  unittestproject:
    image: ${DOCKER_REGISTRY-}unittestproject
    build:
      context: .
      dockerfile: UnitTestProject/Dockerfile
    volumes:
      - ./UnitTestProject/mnt/images:/app/images
      - ./UnitTestProject/mnt/result:/app/result
    networks:
      - selenium-test-nw
    depends_on:
      - selenium-server

  selenium-server:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - selenium-test-nw

networks:
  selenium-test-nw:
    external: false